version: '3'
services:
  test:
    build:
      context: .
      target: test
    volumes:
      - .:/app
    command: python -m pytest

  web:
    build:
      context: .
      target: prod
    volumes:
      - .:/app
    ports:
      - 8080:8080
    network_mode: host